kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nexabank
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # frontend
        hostPort: 8088
        protocol: TCP
      - containerPort: 30500   # backend API
        hostPort: 5000
        protocol: TCP
