# Ensures at least 1 backend pod is always available during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: nexabank
  labels:
    app: nexabank
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend

---
# Ensures at least 1 frontend pod is always available during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: nexabank
  labels:
    app: nexabank
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
