apiVersion: v1
kind: ResourceQuota
metadata:
  name: nexabank-quota
  namespace: nexabank
  labels:
    app: nexabank
spec:
  hard:
    # Compute
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "8"
    limits.memory: "8Gi"
    # Pods and objects
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    secrets: "10"
    configmaps: "10"
