# ---------- SERVICE ACCOUNTS (least-privilege, one per service) ----------

apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: nexabank
  labels:
    app: nexabank
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: nexabank
  labels:
    app: nexabank
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: nexabank
  labels:
    app: nexabank
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-sa
  namespace: nexabank
  labels:
    app: nexabank
automountServiceAccountToken: false
